version: '3.9'
services:
  php-apache-laravel:
    container_name: php-apache-laravel
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "8080:80"

  php-mysql-laravel:
    container_name: php-mysql-laravel
    image: mysql:8.0.35
    stdin_open: true
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel
      - MYSQL_DATABASE=laravel_db
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
